export const authTypes = {
	USER: 'USER',
	ALL: 'All',
	GROUP_REQUESTS: 'GROUP_REQUESTS',
	SIGNIN_REQUEST: 'SIGNIN_REQUEST',
	SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
	SIGNIN_FAIL: 'SIGNIN_FAIL',
	SIGNIN_RESET: 'SIGNIN_RESET',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

	UPDATE_AVATAR_SUCCESS: 'UPDATE_AVATAR_SUCCESS',
	UPDATE_COVER_IMAGE_SUCCESS: 'UPDATE_COVER_IMAGE_SUCCESS',
	SET_PASSWORD_SUCCESS: 'SET_PASSWORD_SUCCESS',
};
