export const conversationTypes = {
	GET_ALL_CONVERSATION_SUCCESS: 'GET_ALL_CONVERSATION_SUCCESS',
	// ADD_CONVERSATION: 'ADD_CONVERSATION',
	ADD_OR_UPDATE_CONVERSATION: 'ADD_OR_UPDATE_CONVERSATION',
	// CREATE_STORY_REQUEST: 'CREATE_STORY_REQUEST',
	// CREATE_STORY_SUCCESS: 'CREATE_STORY_SUCCESS',
	// CREATE_STORY_FAIL: 'CREATE_STORY_FAIL',
	// COMMENT_STORY_SUCCESS: 'COMMENT_STORY_SUCCESS',
	// REACT_STORY_SUCCESS: 'REACT_STORY_SUCCESS',
};
