export const friendTypes = {
	FRIEND_GET_ALL_SUCCESS: 'FRIEND_GET_SUCCESS',
	FRIEND_GET_RECEIVE_REQUESTS_SUCCESS: 'FRIEND_GET_RECEIVE_REQUESTS_SUCCESS',
	FRIEND_GET_SEND_REQUESTS_SUCCESS: 'FRIEND_GET_SEND_REQUESTS_SUCCESS',
	FRIEND_GET_ALL_REQUESTS_SUCCESS: 'FRIEND_GET_ALL_REQUESTS_SUCCESS',
	FRIEND_CREATE_REQUEST_SUCCSESS: 'FRIEND_CREATE_REQUEST_SUCCSESS',
	FRIEND_DELETE_REQUEST_SUCCSESS: 'FRIEND_DELETE_REQUEST_SUCCSESS',
	FRIEND_UPDATE_REQUEST_SUCCSESS: 'FRIEND_UPDATE_REQUEST_SUCCSESS',

	FRIEND_BUTTON_LOADING: 'FRIEND_BUTTON_LOADING',
};
