export const groupTypes = {
	CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
	CREATE_GROUP_RESET: 'CREATE_GROUP_RESET',
	GET_GROUP_REQUESTS_SUCCESS: 'GET_GROUP_REQUESTS_SUCCESS',
	GET_OWN_GROUPS_SUCCESS: 'GET_OWN_GROUPS_SUCCESS',
	UPDATE_REQUEST: 'UPDATE_REQUEST',
	CREATE_REQUEST: 'CREATE_REQUEST',
	DELETE_REQUEST: 'DELETE_REQUEST',
};
