export const notifyTypes = {
	GET_ALL_NOTIFIES_SUCCESS: 'GET_ALL_NOTIFIES_SUCCESS',
	READ_NOTIFY_SUCCESS: 'READ_NOTIFY_SUCCESS',
	NOTIFY_SOUND: 'NOTIFY_SOUND',
	NOTIFY_PUSH: 'NOTIFY_PUSH',
	ADD_NOTIFY: 'ADD_NOTIFY',
};
