export const storyTypes = {
	GET_HOME_STORIES_SUCCESS: 'GET_HOME_STORIES_SUCCESS',
	CREATE_STORY_REQUEST: 'CREATE_STORY_REQUEST',
	CREATE_STORY_SUCCESS: 'CREATE_STORY_SUCCESS',
	CREATE_STORY_FAIL: 'CREATE_STORY_FAIL',
	COMMENT_STORY_SUCCESS: 'COMMENT_STORY_SUCCESS',
	REACT_STORY_SUCCESS: 'REACT_STORY_SUCCESS',
	STORY_PROFILE: 'STORY_PROFILE',
};
